apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jobs  
configMapGenerator:
  - name: prow-config
    namespace: apps
    behavior: create
    options:
      disableNameSuffixHash: true
    files:
      - config.yaml
  - name: prow-labels-config
    namespace: apps
    behavior: create
    options:
      disableNameSuffixHash: true
    files:
      - labels.yaml
  - name: prow-plugins
    namespace: apps
    behavior: create
    options:
      disableNameSuffixHash: true
    files:
      - plugins.yaml
  - name: prow-external-plugins-config
    namespace: apps
    behavior: create
    options:
      disableNameSuffixHash: true
    files:
      - external_plugins_config.yaml

