periodics:
  - name: periodic-configs-autobump
    # Run at minute 5 past every hour from 13 through 20 on every Saturday (At UTC+8 timezone).
    cron: "05 5-12 * * 6"
    always_run: true
    decorate: true
    extra_refs:
      # Check out the repo containing the config and deployment files for your Prow instance.
      - org: ti-community-infra
        repo: configs
        base_ref: main
    max_concurrency: 1
    spec:
      containers:
        - image: gcr.io/k8s-prow/generic-autobumper:v20210927-dcb18f49a5
          command:
            - /app/prow/cmd/generic-autobumper/app.binary
          args:
            - --config=prow/autobump-config/configs-prow-component-autobump-config.yaml
          volumeMounts:
            - name: github-token
              mountPath: /etc/github
              readOnly: true
      volumes:
        - name: github-token
          secret:
            secretName: github-token