apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: ${PROWJOB_NAMESPACE}
  name: prow-label-sync-pingcap
spec:
  schedule: "30 12 * * *" # Every day 12:30
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: prow-label-sync-pingcap
    spec:
      template:
        spec:
          containers:
            - name: label-sync
              image: ticommunityinfra/label_sync:v20230621-df5abce
              args:
                - --confirm=true
                - --config=/etc/config/labels.yaml
                - --github-app-id=$(GITHUB_APP_ID)
                - --github-app-private-key-path=/etc/github/app-private-key
                - --github-endpoint=http://prow-ghproxy
                - --github-endpoint=https://api.github.com
                - --only=pingcap/community,pingcap/docs,pingcap/docs-cn,pingcap/docs-tidb-operator,pingcap/tidb,pingcap/tiflow,pingcap/tiflash
              env:
                - name: GITHUB_APP_ID
                  valueFrom:
                    secretKeyRef:
                      key: app-id
                      name: prow-github
              volumeMounts:
                - name: github
                  mountPath: /etc/github
                  readOnly: true
                - name: config
                  mountPath: /etc/config
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: github
              secret:
                secretName: prow-github
            - name: config
              configMap:
                name: prow-labels-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: ${PROWJOB_NAMESPACE}
  name: prow-label-sync-tikv
spec:
  schedule: "30 8 * * *" # Every day 8:30
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: prow-label-sync-tikv
    spec:
      template:
        spec:
          containers:
            - name: label-sync
              image: ticommunityinfra/label_sync:v20230621-df5abce
              args:
                - --confirm=true
                - --config=/etc/config/labels.yaml
                - --github-app-id=$(GITHUB_APP_ID)
                - --github-app-private-key-path=/etc/github/app-private-key
                - --github-endpoint=http://prow-ghproxy
                - --github-endpoint=https://api.github.com
                - --only=tikv/pd,tikv/tikv,tikv/client-c,tikv/client-go,tikv/client-rust,tikv/raft-engine,tikv/rocksdb,tikv/rust-rocksdb
              env:
                - name: GITHUB_APP_ID
                  valueFrom:
                    secretKeyRef:
                      key: app-id
                      name: prow-github
              volumeMounts:
                - name: github
                  mountPath: /etc/github
                  readOnly: true
                - name: config
                  mountPath: /etc/config
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: github
              secret:
                secretName: prow-github
            - name: config
              configMap:
                name: prow-labels-config
