---
gitHubLogin: "ti-chi-bot"
gitHubToken: "/etc/github/token"
gitName: "ti-chi-bot"
gitEmail: "ti-community-prow-bot@tidb.io"
skipPullRequest: false
gitHubOrg: "ti-community-infra"
gitHubRepo: "configs"
remoteName: "configs"
includedConfigPaths:
  - "."
targetVersion: "latest"
prefixes: []
