apiVersion: v1
kind: Service
metadata:
  labels:
    app: cherrypicker
  namespace: prow
  name: cherrypicker
spec:
  selector:
    app: cherrypicker
  ports:
    - port: 80
      targetPort: 8888
  type: NodePort