apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: prow
  name: jenkins-operator
  labels:
    app: jenkins-operator
    app.kubernetes.io/app: jenkins-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-operator
  labels:
    app: jenkins-operator
    app.kubernetes.io/app: jenkins-operator
rules:
- apiGroups:
  - prow.k8s.io
  resources:
  - prowjobs
  verbs:
  - create
  - get
  - list
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-operator
  labels:
    app: jenkins-operator
    app.kubernetes.io/app: jenkins-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-operator
subjects:
- kind: ServiceAccount
  name: jenkins-operator
  namespace: prow