apiVersion: v1
kind: Service
metadata:
  labels:
    app: prow-controller-manager
  namespace: prow
  name: prow-controller-manager
spec:
  ports:
    - name: metrics
      port: 9090
  selector:
    app: prow-controller-manager
