apiVersion: v1
kind: Service
metadata:
  labels:
    app: ti-community-cherrypicker
  namespace: prow
  name: ti-community-cherrypicker
spec:
  selector:
    app: ti-community-cherrypicker
  ports:
    - port: 80
  type: ClusterIP