apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ti-community-bots
  name: bots-dev
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
spec:
  tls:
    - hosts:
        - bots-dev.tidb.io
  rules:
    - http:
        paths:
          - path: /ti-sync-bot
            backend:
              serviceName: ti-sync-bot
              servicePort: 80